export const ADD_CHILD = 'ADD_CHILD';
export const REMOVE_CHILD = 'REMOVE_CHILD';
export const SET_PROP = 'SET_PROP';

export const ADD_ADULT_TO_HOUSEHOLD = 'ADD_ADULT_TO_HOUSEHOLD';
export const REMOVE_ADULT_FROM_HOUSEHOLD = 'REMOVE_ADULT_FROM_HOUSEHOLD';
export const PATCH_HOUSEHOLD = 'PATCH_HOUSEHOLD';
export const PATCH_HOUSEHOLD_ADULT = 'PATCH_HOUSEHOLD_ADULT';

export const PATCH_CONTACT = 'PATCH_CONTACT';
